version: 2

sphinx:
  configuration: docs/source/conf.py

#mkdocs:
#  configuration: mkdocs.yml
#  fail_on_warning: false

formats:
  - epub
  - pdf
  - htmlzip

python:
  version: 2.7
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
          - docs
  system_packages: true