language: python

os: linux

cache:
  directories:
    - "$HOME/.cache/pip"

python:
  - "3.5.2"

env:
  global:
    - CODECOV_TOKEN="290ba3ff-d885-445d-a8aa-ea7adae29a3c"

install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - python main.py travis
  - coverage run main.py travis
  - coverage report
  - coverage html -d covhtml

after_success:
  - codecov
