language: python

os: linux

cache:
  directories:
    - "$HOME/.cache/pip"

python:
  - "3.5.2"

env:
  global:
    - CODECOV_TOKEN="290ba3ff-d885-445d-a8aa-ea7adae29a3c"

install:
  - pip install codecov
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade setuptools
  - pip install -r requirements.txt

script:
  - python tests/runner.py
  - coverage run tests/runner.py
  - coverage report
  - coverage html -d covhtml

after_success:
  - codecov --token="290ba3ff-d885-445d-a8aa-ea7adae29a3c"
